"""
h4b_moderation_rw.py - Romano-Wolf corrected version of the H4 case-level moderation effects.

**Run:** python src/h4b_moderation_rw.py  (requires the country-year panel; see data/README.md)

============================================================================
Why this step is necessary
============================================================================

The panel-level results in h4_moderation.py were Romano-Wolf corrected (none survived the correction),
but **the 18 case-level tests were not corrected at all**. The previous output contained several attractive
p-values:

    pnci_cpmi x LADDER    -0.4167  p = 0.0000
    swap_line_it x LADDER -0.4621  p = 0.0001
    pnci_equal x UNC     +18.4212  p = 0.0007

These are the smallest p-values among 9 moderators x 2 outcomes = 18 uncorrected tests.
Picking the three with p<0.001 out of 18 tests and citing them is a textbook multiple-testing problem.
This module applies a Romano-Wolf stepdown correction to the whole family of tests jointly.

The key advantage of Romano-Wolf (relative to Bonferroni): it uses the bootstrap distribution of the
**maximum statistic**, and therefore accounts for correlation between tests. The moderators in this project
are highly correlated with one another (e.g. the three PNCI variants, the four RMB infrastructure variables),
so Bonferroni would be overly conservative and Romano-Wolf is more appropriate.

============================================================================
Implementation notes
============================================================================

The null distribution is generated by restricted wild cluster bootstrap: for each test, resampling under
H0: interaction coefficient = 0 yields the null distribution of t. **All tests share the same set of
bootstrap weights** (this is key to the validity of Romano-Wolf - the correlation structure between tests
must be preserved, so the tests cannot be resampled independently).
"""
import numpy as np
import pandas as pd

from config import OUT, SEED
from estimators import _cr1, _design, feols, romano_wolf
from io_load import attach_treatment, build_cohorts, load_cases, load_panel
from pnci_rebuild import add_rebuilt_pnci

FE = ["respondent_iso3", "year"]
CL = "respondent_iso3"

MODERATORS = {
    "pnci_equal": "PNCI: equal-weight composite",
    "pnci_cpmi": "PNCI: CPMI membership (binary)",
    "pnci_network": "PNCI: PageRank network centrality (broken, 80.8% of obs < 0.01)",
    "pnci_rank": "PNCI: PageRank within-year percentile rank (rebuilt, recommended)",
    "pnci_logmm": "PNCI: min-max after log (rebuilt, comparison)",
    "CIPSit": "CIPS direct participant",
    "CIPS_broad_it": "CIPS broad access",
    "rmb_infra_it": "RMB infrastructure (any)",
    "clearing_bank_it": "RMB clearing bank",
    "swap_line_it": "PBoC swap line",
    "unga_align_norm_it": "UNGA alignment",
}
OUTCOMES = ["UNC", "NONICSID", "LADDER"]


def zscore(s):
    s = pd.to_numeric(s, errors="coerce")
    sd = s.std()
    return (s - s.mean()) / sd if sd and sd > 0 else s * 0.0


def run(verbose=True, B=999, seed=SEED):
    p = add_rebuilt_pnci(load_panel())
    c = load_cases()
    g = build_cohorts(p)
    d = attach_treatment(c, g)
    d["UNC"] = d.is_uncitral.astype(float) * 100
    d["NONICSID"] = d.non_icsid.astype(float) * 100
    d["LADDER"] = d.ladder

    key = p.set_index(["iso3", "year"])
    rng = np.random.default_rng(seed)

    # 1) First assemble all tests on **the same sample**, so that the bootstrap weights can be shared.
    #    Moderators have different missingness patterns; a separate dropna for each would break the shared-weights premise.
    base = d.copy()
    for mod in MODERATORS:
        if mod not in p.columns:
            continue
        vals = [key[mod].get((r, y_), np.nan)
                for r, y_ in zip(base.respondent_iso3, base.year)]
        base[f"m__{mod}"] = pd.to_numeric(pd.Series(vals, index=base.index),
                                          errors="coerce")
    mods = [m for m in MODERATORS if f"m__{m}" in base.columns]
    need = [f"m__{m}" for m in mods] + OUTCOMES
    samp = base.dropna(subset=need).copy()
    if len(samp) < 200:
        print(f"Common sample has only {len(samp)} rows, insufficient for the joint correction.")
        return None
    for m in mods:
        samp[f"z__{m}"] = zscore(samp[f"m__{m}"])
        samp[f"i__{m}"] = samp.S * samp[f"z__{m}"]

    cl = pd.factorize(samp[CL].values)[0]
    G = cl.max() + 1

    # 2) Shared bootstrap weights: B x G
    W = rng.choice([-1.0, 1.0], size=(B, G))

    tstats, boot_cols, rows = [], [], []
    for mod in mods:
        for y in OUTCOMES:
            xs = [f"i__{mod}", "S", f"z__{mod}"]
            try:
                r = feols(samp, y, xs, FE, CL)
            except Exception:
                continue
            t_obs = r[f"i__{mod}"]["t"]

            # null distribution of t from restricted wild cluster bootstrap (shared weights W)
            X = _design(samp, xs, FE).values.astype(float)
            yy = samp[y].astype(float).values
            ix = 1                    # const=0, interaction term=1
            XtXi = np.linalg.pinv(X.T @ X)
            keep = [i for i in range(X.shape[1]) if i != ix]
            Xr = X[:, keep]
            br = np.linalg.pinv(Xr.T @ Xr) @ (Xr.T @ yy)
            er = yy - Xr @ br
            fit = Xr @ br
            ts = np.empty(B)
            for b in range(B):
                w = W[b][cl]
                bb, VV, _ = _cr1(X, fit + er * w, cl, XtXi, G)
                ts[b] = bb[ix] / np.sqrt(VV[ix, ix])

            tstats.append(t_obs)
            boot_cols.append(ts)
            rows.append({
                "moderator": mod, "label": MODERATORS[mod], "outcome": y,
                "interaction_perSD": round(r[f"i__{mod}"]["b"], 4),
                "se": round(r[f"i__{mod}"]["se"], 4),
                "t": round(t_obs, 3),
                "p_raw": round(r[f"i__{mod}"]["p"], 4),
                "N": r["_nobs"]})

    tab = pd.DataFrame(rows)
    Bt = np.column_stack(boot_cols)
    tab["p_RomanoWolf"] = np.round(romano_wolf(tstats, Bt), 4)
    tab["p_Bonferroni"] = np.round(
        np.minimum(tab.p_raw * len(tab), 1.0), 4)
    tab["survives_RW_5pct"] = tab.p_RomanoWolf < 0.05
    tab = tab.sort_values("p_raw")

    tab.to_csv(OUT / "h4b_moderation_rw.csv", index=False)

    if verbose:
        print(f"\n=== H4b case-level moderation: joint Romano-Wolf correction ===")
        print(f"  family size = {len(tab)}; common sample N = {len(samp)}; "
              f"bootstrap B = {B}; clusters = {G}")
        print("  All tests share the same set of bootstrap weights, preserving the correlation structure between tests.")
        print(tab.to_string(index=False))
        n_raw = int((tab.p_raw < 0.05).sum())
        n_rw = int(tab.survives_RW_5pct.sum())
        print(f"\n  tests with uncorrected p<0.05: {n_raw}")
        print(f"  surviving Romano-Wolf correction: {n_rw}")
        if n_rw == 0:
            print("\n  Conclusion: none of the case-level moderation effects survives the joint correction.")
            print("  The paper should state 'no robust evidence of heterogeneity was found', rather than cite uncorrected significant terms.")
        else:
            print("\n  Conclusion: the following terms survive the joint correction and may be cited:")
            print(tab[tab.survives_RW_5pct][
                ["moderator", "outcome", "interaction_perSD",
                 "p_raw", "p_RomanoWolf"]].to_string(index=False))
    return tab


if __name__ == "__main__":
    run()
