"""
r22_forum_eligibility.py
========================
**The single highest-priority script in this project at present.**

It answers a question that the existing manuscript does not ask, but that any referee
with a background in investment-arbitration law will certainly raise:

    How much of the measured "shift towards UNCITRAL / away from ICSID"
    is a mechanical consequence of the **States concerned having no ICSID Convention
    jurisdiction at all**, and how much reflects **UNCITRAL being chosen even where
    ICSID was legally available**?

Three outputs
-------------
A. `tab_elig_audit`      -- Convention-status eligibility audit (mechanical eligibility
                            gap between the treated and control groups)
B. `tab_elig_subsample`  -- re-estimates the headline within the subsample in which the
                            Convention is legally available, and estimates the new
                            outcome variable `natcourt_exposed`
C. `tab_elig_decomp`     -- Kitagawa–Oaxaca decomposition:
                            observed shift = choice-set composition
                                           + conditional forum selection

Three possible outcomes, each of which supports a good paper (see the decision tree in docs):
  (i)  conditional-selection term dominates -> the main result is **substantially
       strengthened**; the paper can be framed around routing/selection;
  (ii) composition term dominates          -> the finding is reframed as "sanctions
       co-move with exit from the ICSID Convention architecture", a stronger legal
       finding that maps exactly onto the "denationalisation" theme of
       Track 2 (denationalised finance);
  (iii) both terms comparable              -> report both layers side by side; still an
       upgrade on the current version.

Run (by default fully reuses the project's config / io_load; treatment variable S is
generated by build_cohorts)
----
    python src/r22_forum_eligibility.py --out paper_tables
    python src/r22_forum_eligibility.py --treat-var sanction_fin_count_it --threshold 3

Column names match the project's io_load: respondent_iso3, claimant_iso3, year, rules,
institution, is_uncitral, non_icsid, S, g, et (see _data.COL)
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd

import sys as _sys
_sys.path.insert(0, str(Path(__file__).resolve().parent))
from _compat import (effective_identifying_sample, feols, fmt,  # noqa: E402
                     permutation_test, stars, wild_cluster_bootstrap)
from legal_eligibility import (EligibilityTable, add_enforcement_regime,  # noqa: E402
                               add_forum_availability, eligibility_audit)

PP = 100.0  # scale outcome variables to percentage points


# ==========================================================================
# 1. Estimation wrapper: inference on a par with the headline (CR1 + WCB + permutation)
# ==========================================================================
def estimate_block(df: pd.DataFrame, y: str, treat: str, unit: str,
                   time: str, cohort_map: dict | None = None,
                   controls: list[str] | None = None,
                   label: str = "", B_wcb: int = 1999, B_perm: int = 999,
                   strata: dict | None = None,
                   timing_map: dict | None = None) -> dict:
    controls = list(controls or [])
    d = df.copy()
    d["__y__"] = d[y].astype(float) * PP

    xs = [treat] + controls
    base = feols(d, "__y__", xs, absorb=[unit, time], cluster=unit,
                 target=treat)
    wcb = wild_cluster_bootstrap(d, "__y__", xs, absorb=[unit, time],
                                 cluster=unit, target=treat, B=B_wcb)
    res = {"label": label, "outcome": y, "coef": base["coef"],
           "se": base["se"], "p_cr1": base["p"], "p_wcb": wcb["p_wcb"],
           "n": base["n"], "n_clusters": base["n_clusters"]}

    if cohort_map is not None:
        perm = permutation_test(d, "__y__", absorb=[unit, time], cluster=unit,
                                unit=unit, time=time, cohort_map=cohort_map,
                                controls=controls, strata=strata, B=B_perm)
        res["p_perm"] = perm["p_perm"]
        res["perm_stratified"] = perm["stratified"]
    else:
        res["p_perm"] = np.nan
        res["perm_stratified"] = False
    if timing_map is not None:
        tm = {u: timing_map[u] for u in timing_map if u in set(d[unit])}
        if len(tm) >= 3:
            pt = permutation_test(d, "__y__", absorb=[unit, time], cluster=unit,
                                  unit=unit, time=time, cohort_map=tm,
                                  controls=controls, B=B_perm)
            res["p_perm_timing"] = pt["p_perm"]
        else:
            res["p_perm_timing"] = np.nan
    else:
        res["p_perm_timing"] = np.nan

    ident = effective_identifying_sample(d, treat, unit)
    res.update({"n_switchers": ident["n_clusters_switching"],
                "n_cases_identifying": ident["n_cases_identifying"],
                "switchers": ";".join(ident["switchers"])})
    return res


# ==========================================================================
# 2. Kitagawa–Oaxaca decomposition
# ==========================================================================
def choice_set_decomposition(df: pd.DataFrame, y: str, treat: str,
                             ctype: str = "choice_set_type") -> pd.DataFrame:
    """
    P(y|S=1) - P(y|S=0)
      = Σ_a [π_a(1)-π_a(0)]·P(y|a,S=0)      <- choice-set composition
      + Σ_a π_a(1)·[P(y|a,S=1)-P(y|a,S=0)]  <- conditional forum selection

    Note: this is a **descriptive** decomposition (no fixed effects), intended to give
    readers an interpretable order of magnitude; the fixed-effects version is
    `regression_decomposition`. Both should be reported.
    """
    d = df.dropna(subset=[y, treat, ctype]).copy()
    t1, t0 = d[d[treat] == 1], d[d[treat] == 0]
    cats = sorted(d[ctype].unique())

    pi1 = t1[ctype].value_counts(normalize=True).reindex(cats).fillna(0.0)
    pi0 = t0[ctype].value_counts(normalize=True).reindex(cats).fillna(0.0)
    m1 = t1.groupby(ctype)[y].mean().reindex(cats)
    m0 = t0.groupby(ctype)[y].mean().reindex(cats)

    comp = ((pi1 - pi0) * m0.fillna(0.0)).rename("composition")
    cond = (pi1 * (m1 - m0).fillna(0.0)).rename("conditional")

    out = pd.concat([pi0.rename("share_control"), pi1.rename("share_treated"),
                     m0.rename("rate_control"), m1.rename("rate_treated"),
                     comp, cond], axis=1) * 1.0
    for c in ("composition", "conditional", "rate_control", "rate_treated"):
        out[c] = out[c] * PP
    total = float(t1[y].mean() - t0[y].mean()) * PP
    out.loc["TOTAL"] = {
        "share_control": 1.0, "share_treated": 1.0,
        "rate_control": float(t0[y].mean()) * PP,
        "rate_treated": float(t1[y].mean()) * PP,
        "composition": float(out["composition"].sum()),
        "conditional": float(out["conditional"].sum()),
    }
    out.attrs["raw_gap_pp"] = total
    return out


def regression_decomposition(df: pd.DataFrame, y: str, treat: str, unit: str,
                             time: str, ctype: str = "choice_set_type") -> dict:
    """
    Change in β after adding choice-set-type fixed effects (and their interaction with
    year): the size of the decline is the part attributable to the composition of
    Convention-status eligibility.
    """
    d = df.copy()
    d["__y__"] = d[y].astype(float) * PP
    d["__ct_year__"] = d[ctype].astype(str) + "_" + d[time].astype(str)

    m0 = feols(d, "__y__", [treat], absorb=[unit, time], cluster=unit)
    m1 = feols(d, "__y__", [treat], absorb=[unit, time, ctype], cluster=unit)
    m2 = feols(d, "__y__", [treat], absorb=[unit, "__ct_year__"], cluster=unit)

    return {
        "beta_baseline": m0["coef"], "p_baseline": m0["p"],
        "beta_plus_choiceset_FE": m1["coef"], "p_plus_choiceset_FE": m1["p"],
        "beta_plus_choiceset_x_year_FE": m2["coef"],
        "p_plus_choiceset_x_year_FE": m2["p"],
        "share_explained_by_availability":
            float(1 - m2["coef"] / m0["coef"]) if m0["coef"] else np.nan,
    }


# ==========================================================================
# 3. Does time-varying eligibility explain the distant leads in the event study?
# ==========================================================================
def leads_with_eligibility_control(df: pd.DataFrame, y: str, unit: str,
                                   time: str, event_time: str,
                                   avail: str = "icsid_convention_available"
                                   ) -> pd.DataFrame:
    """
    Diagnostic: add **time-varying** Convention-status eligibility as a control in the
    event study. If the distant lead coefficients (τ ≤ -4) shrink markedly once it is
    added, a substantial part of the Rambachan–Roth breakdown value M̄=0.04 reflects a
    **mechanical pre-trend in legal eligibility** rather than a selection trend. This
    is a control that can be pre-specified and does not amount to p-hacking.
    """
    d = df.dropna(subset=[y, event_time]).copy()
    d["__y__"] = d[y].astype(float) * PP
    tau = d[event_time].astype(float)
    d["lead_far"] = (tau <= -4).astype(float)
    d["post_01"] = tau.between(0, 2).astype(float)
    d["post_3p"] = (tau >= 3).astype(float)
    terms = ["lead_far", "post_01", "post_3p"]

    rows = []
    for spec, ctrl in [("Baseline", []),
                       ("+ time-varying ICSID eligibility", [avail])]:
        dd = d.copy()
        for c in ctrl:
            dd[c] = dd[c].fillna(False).astype(bool).astype(float)
        for t in terms:
            r = feols(dd, "__y__", terms + ctrl, absorb=[unit, time],
                      cluster=unit, target=t)
            rows.append({"spec": spec, "term": t, "coef": r["coef"],
                         "se": r["se"], "p": r["p"]})
    return pd.DataFrame(rows)


# ==========================================================================
# 4. LaTeX export
# ==========================================================================
def to_tex_main(rows: list[dict], path: Path) -> None:
    lines = [r"\begin{tabular}{llrrrrrr}", r"\toprule",
             r"Outcome & Sample & Effect (pp) & (s.e.) & $p_{\text{CR1}}$ & "
             r"$p_{\text{WCB}}$ & $p_{\text{perm}}$ & $N$ \\", r"\midrule"]
    for r in rows:
        lines.append(
            f"{r['outcome_label']} & {r['label']} & "
            f"{fmt(r['coef'])}${stars(r['p_cr1'])}$ & ({fmt(r['se'])}) & "
            f"{fmt(r['p_cr1'], 4)} & {fmt(r['p_wcb'], 3)} & "
            f"{fmt(r['p_perm'], 3)} & {r['n']} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    path.write_text("\n".join(lines), encoding="utf-8")


# ==========================================================================
def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--cases", default=None,
                    help="Optional; defaults to the project config/io_load")
    ap.add_argument("--panel", default=None)
    ap.add_argument("--ref", default=None)
    ap.add_argument("--out", default="paper_tables")
    ap.add_argument("--col-date", default=None,
                    help="Column with the exact filing date (absent in this dataset; "
                         "approximated by year-07-01 when missing)")
    ap.add_argument("--threshold", type=float, default=None)
    ap.add_argument("--treat-var", default=None,
                    help="Override the config treatment variable, e.g. sanction_fin_count_it")
    ap.add_argument("--B-wcb", type=int, default=1999)
    ap.add_argument("--B-perm", type=int, default=999)
    ap.add_argument("--skip-perm", action="store_true")
    args = ap.parse_args()

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    from _data import (COL, cohort_map_from, load_analysis_frame,
                       treated_pre_post_table)
    cases, g = load_analysis_frame(args.cases, args.panel,
                                   threshold=args.threshold,
                                   treat_var=args.treat_var)
    U, T, Y, H = COL["unit"], COL["time"], COL["treat"], COL["home"]

    elig = EligibilityTable.load(args.ref) if args.ref else EligibilityTable.load()
    cases = add_forum_availability(cases, elig, host=U, home=H,
                                   date=args.col_date, year=T)
    cases = add_enforcement_regime(cases, rules=COL["rules"],
                                   institution=COL["institution"])
    cases["is_scc"] = (cases["forum_class"] == "SCC").astype(int)
    unknown = elig.unknown_states()
    if unknown:
        print(f"[warn] States not in the reference table (treated as non-Contracting "
              f"States): {unknown}")

    # --- A. Audit ------------------------------------------------------------
    audit = eligibility_audit(cases, treat=Y, unit=U)
    audit.to_csv(out / "tab_elig_audit.csv", index=False)
    print("\n=== A. Convention-status eligibility audit ===")
    print(audit.round(3).to_string(index=False))

    sw = cases.groupby(U).agg(
        n_cases=(Y, "size"), treated_cases=(Y, "sum"),
        switcher=(Y, lambda s: s.nunique() > 1),
        conv_avail=("icsid_convention_available",
                    lambda s: float(s.fillna(False).mean())),
        af_only=("icsid_af_available", lambda s: float(s.fillna(False).mean())),
        mech_unavail=("icsid_unavailable_mech",
                      lambda s: float(s.fillna(False).mean())),
        uncitral_rate=("is_uncitral", "mean"))
    sw = sw[sw["treated_cases"] > 0].sort_values("treated_cases", ascending=False)
    sw.to_csv(out / "tab_elig_by_switcher.csv")
    print("\n=== A2. Convention-status eligibility of sanctioned respondent States ===")
    print(sw.round(3).to_string())

    print("\n=== A3. Raw 2x2 (UNCITRAL rate, %) ===")
    tt = treated_pre_post_table(cases, "is_uncitral")
    tt.to_csv(out / "tab_raw_2x2_uncitral.csv")
    print(tt.to_string())

    # --- B. Subsample re-estimation -------------------------------------------
    cohort_map = None if args.skip_perm else cohort_map_from(g, cases, U)
    timing_map = None if args.skip_perm else cohort_map_from(g, timing_only=True)
    samples = {
        "Full sample": cases,
        "ICSID Convention legally available": cases[
            cases["icsid_convention_available"].fillna(False).astype(bool)],
        "Excl. mechanically ICSID-ineligible": cases[
            ~cases["icsid_unavailable_mech"].fillna(False).astype(bool)],
        "Excl. Russia": cases[cases[U] != "RUS"],
    }
    outcomes = [("is_uncitral", "UNCITRAL"),
                ("natcourt_exposed", "National-court exposed (non-Convention)"),
                ("convention_regime", "ICSID Convention regime"),
                ("is_scc", "SCC")]
    rows = []
    for ycol, ylab in outcomes:
        for label, sub in samples.items():
            if sub[Y].nunique() < 2 or len(sub) < 30:
                continue
            r = estimate_block(sub, ycol, Y, U, T, cohort_map=cohort_map,
                               label=label, B_wcb=args.B_wcb,
                               B_perm=args.B_perm, timing_map=timing_map)
            r["outcome_label"] = ylab
            rows.append(r)
    res = pd.DataFrame(rows)
    res.to_csv(out / "tab_elig_subsample.csv", index=False)
    to_tex_main(rows, out / "tab_elig_subsample.tex")
    print("\n=== B. Re-estimation conditional on eligibility ===")
    print(res[["outcome_label", "label", "coef", "se", "p_cr1", "p_wcb",
               "p_perm", "p_perm_timing", "n", "n_switchers"]].round(4)
          .to_string(index=False))

    # --- C. Decomposition ------------------------------------------------------
    print("\n=== C. choice-set composition vs conditional selection ===")
    dec = choice_set_decomposition(cases, "is_uncitral", Y)
    dec.to_csv(out / "tab_elig_decomp.csv")
    print(dec.round(3).to_string())
    regdec = regression_decomposition(cases, "is_uncitral", Y, U, T)
    (out / "tab_elig_regdecomp.json").write_text(
        json.dumps(regdec, indent=2), encoding="utf-8")
    print(json.dumps(regdec, indent=2))

    # --- D. Eligibility control in the event study ------------------------------
    et = COL["event_time"]
    if et in cases.columns:
        lead = leads_with_eligibility_control(cases, "is_uncitral", U, T, et)
        lead.to_csv(out / "tab_elig_leads.csv", index=False)
        print("\n=== D. Are the distant leads driven by time-varying eligibility? ===")
        print(lead.round(3).to_string(index=False))

    cases.to_parquet(out / "cases_with_eligibility.parquet", index=False)
    print(f"\n[done] Written to {out.resolve()}")


if __name__ == "__main__":
    main()
